<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Sign In</title>';
echo '<meta charset="utf-8">';
echo '<meta name="description" content="Assignment 1">';
echo '<meta name="keywords" content="HTML5, CSS, JS">';
echo '<meta name="author" content="Tran Khai Kiet">';
echo '<link rel = "stylesheet" href = "styles/login.css">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">';
echo '<link href = 'https://fonts.googleapis.com/css?family=IBM Plex Mono' rel = "stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<header class="header">';
echo '<a href="home.html">';
echo '<img class="logo" alt="logo" src="images/logo.png">';
echo '</a>';
echo '';
echo '<nav class="nav">';
echo '<ul class="nav-list">';
echo '<li><a href="./home.html" class="nav-link"><img class = "nav_home_img" alt = "" src = "images/home_symbol.png">&emsp;Home</a></li>';
echo '<li><a href="./product.html" class="nav-link"><img class = "nav_cooking_img" alt = "" src = "images/cooking.png">&emsp;Recipes</a></li>';
echo '<li><a href="./transaction.html" class="nav-link"><img class = "nav_transaction_img" alt = "" src = "images/transaction_symbol.png">&emsp;Transaction</a></li>';
echo '<li><a href="./login.html" class="nav-link"><img class = "nav_cart_img" alt = "" src = "images/cart_symbol.png">&emsp;Cart</a></li>';
echo '<li><a href="./wallet.html" class="nav-link nav-cta"><img class = "nav_wallet_img" alt = "" src = "images/wallet.png">&emsp;Connect Wallet</a></li>';
echo '</ul>';
echo '</nav>';
echo '</header>';
echo '';
echo '<main>';
echo '<h1 style = "color: #E67E22;" class = "login_introduction">Sign In</h1>';
echo '<p class = "login_introduction">Login your Account to see your Cart.</p>';
echo '<form action="login.php" method="POST">';
echo '<label for="username">Username:</label><br>';
echo '<input type="text" id="username" name="username" required><br><br>';
echo '<label for="password">Password:</label><br>';
echo '<input type="password" id="password" name="password" required><br><br>';
echo '<input class = "login_signin_button" type="submit" value="Sign In">';
echo '</form>';
echo '<a href="register.html"><button>Sign Up</button></a>';
echo '</main>';
echo '';
echo '<footer>';
echo '<div id="footer1">';
echo '<div id="nav_footer">';
echo '<h2><span>EXPLORE</span></h2>';
echo '<div id="explore_footer">';
echo '<p><a href="./home.html"><i class="fa-sharp fa-solid fa-angle-right"></i>Home</a></p>';
echo '<p><a href="./product.html"><i class="fa-sharp fa-solid fa-angle-right"></i>Product</a></p>';
echo '<p><a href="./transaction.html"><i class="fa-sharp fa-solid fa-angle-right"></i>Transaction</a></p>';
echo '<p><a href="./login.html"><i class="fa-sharp fa-solid fa-angle-right"></i>Cart</a></p>';
echo '<p><a href="./wallet.html"><i class="fa-sharp fa-solid fa-angle-right"></i>Connect Wallet</a></p>';
echo '</div>';
echo '</div>';
echo '<div id="overall">';
echo '<h2><span>ABOUT</span></h2>';
echo '<p><a href="./home.html">The Company</a></p>';
echo '<p><a href="#">FAQ</a></p>';
echo '<p><a href="#">Privacy Policy</a></p>';
echo '</div>';
echo '<div id="icons">';
echo '<h2><span>FOLLOW US</span></h2>';
echo '<a href="#"><i class="fa-brands fa-facebook"></i></a>';
echo '<a href="#"><i class="fa-brands fa-twitter"></i></a>';
echo '<a href="#"><i class="fa-brands fa-youtube"></i></a>';
echo '</div>';
echo '</div>';
echo '<div id="footer2">';
echo '<p><i class="fa-solid fa-copyright"></i>2023 Foodie. ALL RIGHTS RESERVED.</p>';
echo '<img src="images/logo.png" alt="logo">';
echo '</div>';
echo '</footer>';
echo '</body>';
echo '</html>';
?>