<header class="header">
    <a href="./home.php">
        <img class="logo" alt="logo" src="./images/logo.png">
      </a>

    <nav class="nav">
        <ul class="nav-list">
            <li><a href="./home.php" class="nav-link"><img class = "nav_home_img" alt = "" src = "images/home_symbol.png">&emsp;Home</a></li>
            <li><a href="./product.php" class="nav-link"><img class = "nav_cooking_img" alt = "" src = "images/cooking.png">&emsp;Recipes</a></li>
            <li><a href="./upload.php" class="nav-link"><img class = "nav_upload_img" alt = "" src = "images/upload_symbol.png">&emsp;Upload</a></li>
            <li><a href="./cart.php" class="nav-link"><img class = "nav_cart_img" alt = "" src = "images/cart_symbol.png">&emsp;Cart</a></li>
            <li><a href="./login.php" class="nav-link nav-cta"><img class = "nav_login_img" alt = "" src = "images/login_symbol.png">&emsp;User</a></li>          
        </ul>
    </nav>
</header>